# Generated by Django 5.2.3 on 2025-06-12 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('telefone', models.CharField(max_length=19, unique=True)),
                ('nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('descricao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=14, null=True, unique=True)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('telefone', models.CharField(max_length=19, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('telefone', models.CharField(max_length=19, unique=True)),
                ('nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sala', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('faixaEtaria', models.IntegerField()),
                ('dosagem', models.CharField(max_length=45)),
                ('intervalos', models.IntegerField()),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clinica.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cim', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('telefone', models.CharField(max_length=19, unique=True)),
                ('nascimento', models.DateField()),
                ('entrada', models.DateField()),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clinica.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('atendente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clinica.atendente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.paciente')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicioDosagem', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.consulta')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.consulta')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.medico')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.sala')),
            ],
        ),
    ]
